version: 2

jobs:
  test-2.7: &test_template
    docker:
      - image: circleci/python:2.7.17
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
            pip install --user --quiet numpy
            pip install --user --quiet pytest scipy scikit-learn -e .
      - run:
          name: Running tests
          command: pytest --strict --junit-xml /tmp/test_results/pytest/results.xml
      - store_test_results:
          path: /tmp/test_results

  test-3.5:
    <<: *test_template
    docker:
      - image: circleci/python:3.5.9

  test-3.6:
    <<: *test_template
    docker:
      - image: circleci/python:3.6.10

  test-3.7:
    <<: *test_template
    docker:
      - image: circleci/python:3.7.6

  test-3.8:
    <<: *test_template
    docker:
      - image: circleci/python:3.8.1

  lint:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
            pip install --user flake8 black
      - run:
          name: Linting
          command: flake8 --count
      - run:
          name: Black
          command: black --check .

workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.5
      - test-3.6
      - test-3.7
      - test-3.8
      - lint
